"""empty message

Revision ID: 017b88e7d5d5
Revises: 669013a92774
Create Date: 2019-08-23 15:16:34.622548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017b88e7d5d5'
down_revision = '669013a92774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('score', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'courses', ['score'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'score')
    # ### end Alembic commands ###
