"""empty message

Revision ID: 13dbdd8d9004
Revises: cd6d78879262
Create Date: 2019-08-23 15:31:24.570450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13dbdd8d9004'
down_revision = 'cd6d78879262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('score', table_name='courses')
    op.drop_column('courses', 'score')
    op.drop_index('age', table_name='students')
    op.drop_column('students', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', mysql.VARCHAR(length=3), nullable=True))
    op.create_index('age', 'students', ['age'], unique=True)
    op.add_column('courses', sa.Column('score', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('score', 'courses', ['score'], unique=True)
    # ### end Alembic commands ###
